<?php
$sql = "INSERT INTO m1(
reg_card_id,
reg_name_title,
reg_name_id,
reg_name,
reg_suname,
reg_date,
reg_email,
reg_no,
reg_road,
reg_tambol,
reg_tambol_id,
reg_amphoe,
reg_amphoe_id,
reg_province,
reg_province_id,
reg_postcode,
reg_tel,
father_name,
father_suname,
father_job,
father_tel,
mother_title,
mother_name,
mother_suname,
mother_job,
mother_tel,
parent_title,
parent_name,
parent_suname,
relationship,
parent_tel,
old_school_name,
old_school_amphoe,
old_school_amphoe_id,
old_school_province,
old_school_province_id,
file_name_1,
file_name_1_status,
file_name_2,
file_name_2_status,
file_name_3,
file_name_3_status,
file_name_4,
file_name_4_status,
file_name_5,
file_name_5_status,
file_name_9,
file_name_9_status,
record_time,
onet_status,
reg_ip_address
) VALUES (
'" . $_POST['reg_card_id'] . "',
'" . $_POST['reg_name_title'] . "',
'" . $_POST['reg_name_id'] . "',
'" . $_POST['reg_name'] . "',
'" . $_POST['reg_suname'] . "',
'" . $yyyymmdd . "',
'" . $_POST['reg_email'] . "',
'" . $_POST['reg_no'] . "',
'" . $_POST['reg_road'] . "',
'" . $dis[1] . "',
'" . $dis[0] . "',
'" . $am[1] . "',
'" . $am[0] . "',
'" . $prov[1] . "',
'" . $prov[0] . "',
'" . $am[2] . "',
'" . $_POST['reg_tel'] . "',
'" . $_POST['father_name'] . "',
'" . $_POST['father_suname'] . "',
'" . $_POST['father_job'] . "',
'" . $_POST['father_tel'] . "',
'" . $_POST['mother_title'] . "',
'" . $_POST['mother_name'] . "',
'" . $_POST['mother_suname'] . "',
'" . $_POST['mother_job'] . "',
'" . $_POST['mother_tel'] . "',
'" . $_POST['parent_title'] . "',
'" . $_POST['parent_name'] . "',
'" . $_POST['parent_suname'] . "',
'" . $_POST['relationship'] . "',
'" . $_POST['parent_tel'] . "',
'" . $_POST['old_school_name'] . "',
'" . $am_3[1] . "',
'" . $am_3[0] . "',
'" . $prov_3[1] . "',
'" . $prov_3[0] . "',
'" . $new_image_name . "',
'" . $status_file1 . "',
'" . $new_file02_name . "',
'" . $status_file2 . "',
'" . $new_file03_name . "',
'" . $status_file3 . "',
'" . $new_file04_name . "',
'" . $status_file4 . "',
'" . $new_file05_name . "',
'" . $status_file5 . "',
'" . $new_file09_name . "',
'" . $status_file9 . "',
'" . $o_net_status . "',
'" . $rec_date . "',
'" . $ipaddress . "'
)";
